{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kanrigate.fullname" . }}
  labels:
    {{- include "kanrigate.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kanrigate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kanrigate.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
