apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanrigate.fullname" . }}
  labels:
    {{- include "kanrigate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: 3000
      protocol: TCP
      name: frontend
    - port: {{ .Values.service.backendPort }}
      targetPort: 3232
      protocol: TCP
      name: backend
  selector:
    {{- include "kanrigate.selectorLabels" . | nindent 4 }}
