{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "template-cluster-resources___admin") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-cluster-resources___admin
rules:
- verbs:
  - get
  - list
  - watch
  nonResourceURLs:
  - /metrics
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - namespaces/finalize
  - namespaces/status
  - nodes
  - nodes/proxy
  - nodes/status
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - persistentvolumes
  - persistentvolumes/status
  - pods
  - pods/attach
  - pods/binding
  - pods/eviction
  - pods/exec
  - pods/log
  - pods/proxy
  - pods/status
  - podtemplates
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  - serviceaccounts
  - services
  - services/proxy
  - services/status
- verbs:
  - list
  - get
  - watch
  apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - daemonsets/status
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - csinodes
  - storageclasses
  - volumeattachments
  - volumeattachments/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - events.k8s.io
  resources:
  - events
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  - apiservices/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  - podsecuritypolicies
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - componentstatuses
  - namespaces
  - nodes
  - persistentvolumes
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - customresourcedefinitions
  - apiservices
  - tokenreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  - certificatesigningrequests
  - runtimeclasses
  - podsecuritypolicies
  - clusterrolebindings
  - clusterroles
  - priorityclasses
  - csidrivers
  - csinodes
  - storageclasses
  - volumeattachment
{{- end }}
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "template-cluster-resources___read-only") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-cluster-resources___read-only
rules:
- verbs:
  - get
  - list
  - watch
  nonResourceURLs:
  - /metrics
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - namespaces/finalize
  - namespaces/status
  - nodes
  - nodes/proxy
  - nodes/status
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - persistentvolumes
  - persistentvolumes/status
  - pods
  - pods/attach
  - pods/binding
  - pods/eviction
  - pods/exec
  - pods/log
  - pods/proxy
  - pods/status
  - podtemplates
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  - serviceaccounts
  - services
  - services/proxy
  - services/status
- verbs:
  - list
  - get
  - watch
  apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - daemonsets/status
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - csinodes
  - storageclasses
  - volumeattachments
  - volumeattachments/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - events.k8s.io
  resources:
  - events
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  - apiservices/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  - podsecuritypolicies
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - componentstatuses
  - namespaces
  - nodes
  - persistentvolumes
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - customresourcedefinitions
  - apiservices
  - tokenreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  - certificatesigningrequests
  - runtimeclasses
  - podsecuritypolicies
  - clusterrolebindings
  - clusterroles
  - priorityclasses
  - csidrivers
  - csinodes
  - storageclasses
  - volumeattachment
{{- end }}
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "template-namespaced-resources___developer") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___developer
rules:
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/portforward
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - services
  - events
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  - networkpolicies
  - poddisruptionbudgets
{{- end }}
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "template-namespaced-resources___monitoring") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___monitoring
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/portforward
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - services
  - events
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  - networkpolicies
  - poddisruptionbudgets
  - jobs
  - cronjobs
{{- end }}
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "template-namespaced-resources___operation") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___operation
rules:
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - '*'
{{- end }}
